### PR TITLE
Organized transcription data

### PR DESCRIPTION
**Pull request by ghost**
I've organized the transcription data into CSVs. Because of how different each .txt file is, I had to manually assign the geographic location. If one did not exist, I labelled it "NA". More notes are in a file called "Notes About Conversions.txt" in the folder with all the files I've uploaded (including the Jupyter notebook that has my conversion code). One thing I forgot to add in the .txt was that you'll need to manually put in the header labels, but otherwise everything else is arranged the way you wanted it.

### CODE REVIEW

**Comment by dabao12321** [comment]
Thank you for contributing! I know Sarah had encoding issues with 37 and 60, so don't worry about those– I'll address them this weekend. 

For solo speakers (#21, 25, 26, 27, 30, 32, 38, 40, 54), could you make a modified notebook/parser to convert it to the .csv format? Hopefully most of your code can be reused by setting the speaker/location as a non-changing value and then applying similar cleaning methods. 

Cleaning things: 
- filter out the "X" or 'XX*' values (never seem to have much value)
- are the commented-out `elifs` in your notebook supposed to be there? Please add some more documentation there, and remove unnecessary code!

**Comment by ghost** [comment]
Regarding the `elifs`, basically I hardcoded which person was from which geographic origin because there were duplicates. So I'd go through this [link](http://www.linguistics.ucsb.edu/research/santa-barbara-corpus#Contents) (where you got the original files from) to figure out how many characters were in the .txt file and then run a bunch of `if-elif` statements to assign the geographic origin accordingly. Also, in my Jupyter notebook, I've commented out a lot of print statements because whenever bugs would arise, I would uncomment them to figure out where the error was. I'll document the code a bit better to explain all of this. I can remove these comments if you want?

Regarding the solo speakers, I think the simplest fix would be to edit the metadata files and add the transition names (like "ENF" or "AUD"). Then, I believe the code should pick up the speakers because it'll "see" 2+ speakers. For filtering the specific values ("X", "XX*", etc), I'll see what I can do; however, there's a wide variety of them.

Lastly, not sure if I mentioned it earlier but I rewrote most of the metadata CSVs because they weren't formatted correctly and renamed them with an 'a' at the end.

**Comment by dabao12321** [comment]
1) Got it– in that case, just document it clearly and leave the list of names commented out, since might need to rerun it all at some point. As for the debugging comments, if they are no longer necessary/bugs fixed, I think you can remove them. 

2) I actually may be able to fix the 'X' problem using NLTK in the later stages of processing, so don't worry about that. Instead, could you try adding the transition names and see if it works? 

3) Noted! Thank you!

**Comment by ghost** [comment]
1. I removed the comments & added more documentation.
2. My idea worked so I've uploaded them. For #32 and #38, the speakers were named as NAME_1, NAME_2, etc and my program was splitting the names on the underscore so it would read NAME, NAME, etc. So, I edited the original .txt files and labeled them as A, B, C, etc and without the underscores. I also reuploaded the metadata files and the Jupyter notebook.

**Pull request merged**
